### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by Saverton** [learn-co-curriculum/hash-table#2]
### Canvas Link

https://learning.flatironschool.com/courses/5253/pages/day-4-underneath-hashes?module_item_id=484260

### Concern

In the last Paragraph of the 'Hash Tables' section, the lesson refers to constant time, but provides the notation O(n) instead of O(1)

### Suggested Changes

Change O(n) => O(1)

**Comment by lizbur10** [comment]
Thanks @Saverton ! This should now be fixed 💙
